# datasource info
spring:
  datasource:
    url: jdbc:mysql://120.79.130.100:3306/tea_club
    username: root
    password: Family123@foxmail.com
    # 配置redis主机地址
  redis:
    host: 120.79.130.100
  mvc:
    hiddenmethod:
      filter:
        enabled: true

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml

logging:
  level:
    com.yuyi.tea.mapper: debug