# datasource info
spring:
  datasource:
    url: jdbc:mysql://120.79.130.100:3306/tea_club
    username: root
    password: Family123@foxmail.com
    # 配置redis主机地址
  redis:
    host: 120.79.130.100
  mvc:
    hiddenmethod:
      filter:
        enabled: true



mybatis:
  configuration:
    map-underscore-to-camel-case: true
#  type-handlers-package: com.yuyi.tea.typehandler
#  # 指定全局配置文件位置
#  config-location: classpath:mybatis/mybatis-config.xml
#  # 指定sql映射文件位置
#  mapper-locations: classpath:mybatis/mapper/*.xml
#  #  配置项目中实体类包路径
#  type-aliases-package: com.yuyi.tea.bean

logging:
  level:
    com.yuyi.tea.mapper: debug